#!/usr/bin/env bash
#
# Secures OpenSSHD

# disable root ssh logins
sed -i "s|[#]*PermitRootLogin.*|PermitRootLogin no|g" "/etc/ssh/sshd_config"


# restart the sshd service
systemctl restart sshd.service
